use_frameworks!


source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMUserCenterServices_Example' do
  pod 'AHFMUserCenterServices', :path => '../'

  target 'AHFMUserCenterServices_Tests' do
    inherit! :search_paths

    
  end
end
